# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CgIC7oEUcJZVi1JZ3P-80q8wxD4GRgua
"""

cost_taxi=0
cost=0
cost_hotel=0
def vuelo():
    vuel = int(input("¿Desea vuelo sencillo(1) o redondo (0)?" ))
    while vuel > 2:
      vuel = int(input("¿Desea vuelo sencillo(1) o redondo (0)?" ))
    if vuel == 1:
      print("Esta es nuestra lista de vuelos sencillos: ")
      print("1.Monterrey - Isla Holbox")
      print("2.Monterrey - Puerto Escondido")
      print("3.Monterrey - Rivera Maya")
      print("4.Monterrey - Los Cabos")
      print("5.Monterrey - Huatulco")
      print("6.Guadalajara - Isla Holbox")
      print("7.Guadalajara - Puerto Escondido")
      print("8.Guadalajara - Rivera Maya")
      print("9.Guadalajara - Los Cabos")
      print("10.Guadalajara - Huatulco")
      print("11.Ciudad de México - Isla Holbox")
      print("12.Ciudad de México - Puerto Escondido")
      print("13.Ciudad de México - Rivera Maya")
      print("14.Ciudad de México - Los Cabos")
      print("15.Ciudad de México - Huatulco")
      num_vuel= int(input("¿Qué número de vuelo desea? "))
      while num_vuel>15:
        num_vuel= int(input("¿Qué número de vuelo desea? "))
    else:
      print("Esta es nuestra lista de vuelos redondos: ")
      print("16.Monterrey - Isla Holbox")
      print("17.Monterrey - Puerto Escondido")
      print("18.Monterrey - Rivera Maya")
      print("19.Monterrey - Los Cabos")
      print("20.Monterrey - Huatulco")
      print("21.Guadalajara - Isla Holbox")
      print("22.Guadalajara - Puerto Escondido")
      print("23.Guadalajara - Rivera Maya")
      print("24.Guadalajara - Los Cabos")
      print("25.Guadalajara - Huatulco")
      print("26.Ciudad de México - Isla Holbox")
      print("27.Ciudad de México - Puerto Escondido")
      print("28.Ciudad de México - Rivera Maya")
      print("29.Ciudad de México - Los Cabos")
      print("30.Ciudad de México - Huatulco") 
      num_vuel= int(input("¿Qué número de vuelo desea? "))
      while num_vuel>30 or num_vuel<15:
        num_vuel= int(input("¿Qué número de vuelo desea? "))
    if num_vuel == 1:
      cost=pers * 934
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 2:
      cost=pers * 1150
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 3:
      cost=pers * 980
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 4:
      cost=pers * 1500
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 5:
      cost=pers * 965
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 6:
      cost=pers * 500
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 7:
      cost=pers * 975
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 8:
      cost=pers * 960
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 9:
      cost=pers * 500
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 10:
      cost=pers * 1320
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 11:
      cost=pers * 1150
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 12:
      cost=pers * 967
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 13:
      cost=pers * 450
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 14:
      cost=pers * 587
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 15:
      cost=pers * 670
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 16:
      cost=pers * 2000
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 17:
      cost=pers * 2918
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 18:
      cost=pers * 1208
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 19:
      cost=pers * 1857
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 20:
      cost=pers * 987
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 21:
      cost=pers * 2089
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 22:
      cost=pers * 3000
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 23:
      cost=pers * 876
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 24:
      cost=pers * 1345
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 25:
      cost=pers * 2300
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 26:
      cost=pers * 1456
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 27:
      cost=pers * 1560
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 28:
      cost=pers * 1484
      print("El costo de sus vuelos es de $", cost)
    elif num_vuel == 29:
      cost=pers * 1890
      print("El costo de sus vuelos es de $", cost)
    else:
      cost=pers * 890
      print("El costo de sus vuelos es de $", cost)
    return cost
    
def hotel():
  print("Esta es nuestra lista de ciudades: ")
  print("1.Huatulco")
  print("2.Isla Holbox")
  print("3.Los Cabos")
  print("4.Puerto Escondido")
  print("5.Rivera Maya")
  num_ciud=int(input("¿A qué número de ciudad se dirige? "))
  while num_ciud > 5:
    num_ciud=int(input("¿A qué número de ciudad se dirige? "))
  if num_ciud==1:
    print("Los hoteles disponibles en Huatulco son: ")
    print("1.Barceló")
    print("2.Secrets")
    print("3.Las Brisas")
    print("4.Isla Natura")
    print("5.Dreams")
  elif num_ciud==2:
    print("Los hoteles disponibles en Isla Holbox son: ")
    print("6.Villas Paraíso del Mar")
    print("7.Puerto Holbox")
    print("8.Villas Tiburón")
    print("9.Cielito Lindo")
    print("10.Xalot Resorts")
  elif num_ciud==3:
    print("Los hoteles disponibles en Los Cabos son: ")
    print("11.Pueblo Bonito Villas")
    print("12.Hacienda Beach Club")
    print("13.Las Ventanas Resort")
    print("14.Gran Velas Resort")
    print("15.Montage Los Cabos")
  elif num_ciud==4:
    print("Los hoteles disponibles en Puerto Escondido son: ")
    print("16.Hotel Escondido")
    print("17.Shavanna Boutique")
    print("18.Villas carizalillo")
    print("19.Vivo Resort")
    print("20.Suits la HAcienda")
  else:
    print("Los hoteles disponibles en Rrivera Maya son: ")
    print("21.Iberostar Playa Mita")
    print("22.casa Mita")
    print("23.Grand Velas")
    print("24.Four Season Resort")
    print("25.Marival Luxury")
  num_hotel=int(input("Qué opción de hotel desea?"))
  while num_hotel > 25:
    num_hotel=int(input("Qué opción de hotel desea?"))
  if num_hotel==1:
    cost_hotel=10000
    print("El precio por noche del hotel para", pers, " personas es de $", cost_hotel)
  elif num_hotel==2:
    cost_hotel=18000
    print("El precio por noche del hotel para", pers, " personas es de $18,000")
  elif num_hotel==3:
    cost_hotel=23000
    print("El precio por noche del hotel para", pers, " personas es de $23,000")
  elif num_hotel==4:
    cost_hotel=27000
    print("El precio por noche del hotel para", pers, " personas es de $27,000")
  elif num_hotel==5:
    cost_hotel=34000
    print("El precio por noche del hotel para", pers, " personas es de $34,000")
  elif num_hotel==6:
    cost_hotel=5900
    print("El precio por noche del hotel para", pers, " personas es de $5,900")
  elif num_hotel==7:
    cost_hotel=7890
    print("El precio por noche del hotel para", pers, " personas es de $7890")
  elif num_hotel==8:
    cost_hotel=8700
    print("El precio por noche del hotel para", pers, " personas es de $8,700")
  elif num_hotel==9:
    cost_hotel=10600
    print("El precio por noche del hotel para", pers, " personas es de $10,600")
  elif num_hotel==10:
    cost_hotel=10999
    print("El precio por noche del hotel para", pers, " personas es de $10,999")
  elif num_hotel==11:
    cost_hotel=15765
    print("El precio por noche del hotel para", pers, " personas es de $15,765")
  elif num_hotel==12:
    cost_hotel=20000
    print("El precio por noche del hotel para", pers, " personas es de $20,000")
  elif num_hotel==13:
    cost_hotel=26890
    print("El precio por noche del hotel para", pers, " personas es de $26,890")
  elif num_hotel==14:
    cost_hotel=40000
    print("El precio por noche del hotel para", pers, " personas es de $40,000")
  elif num_hotel==15:
    cost_hotel=4999
    print("El precio por noche del hotel para", pers, " personas es de $4,999")
  elif num_hotel==16:
    cost_hotel=6750
    print("El precio por noche del hotel para", pers, " personas es de $6,750")
  elif num_hotel==17:
    cost_hotel=8789
    print("El precio por noche del hotel para", pers, " personas es de $8,789")
  elif num_hotel==18:
    cost_hotel=10789
    print("El precio por noche del hotel para", pers, " personas es de $10,789")
  elif num_hotel==19:
    cost_hotel=13456
    print("El precio por noche del hotel para", pers, " personas es de $13,456")
  elif num_hotel==20:
    cost_hotel=8890
    print("El precio por noche del hotel para", pers, " personas es de $8,860")
  elif num_hotel==21:
    cost_hotel=8900
    print("El precio por noche del hotel para", pers, " personas es de $8,900")
  elif num_hotel==22:
    cost_hotel=15000
    print("El precio por noche del hotel para", pers, " personas es de $15,000")
  elif num_hotel==23:
    cost_hotel=20000
    print("El precio por noche del hotel para", pers, " personas es de $20,000")
  elif num_hotel==24:
    cost_hotel=20900
    print("El precio por noche del hotel para", pers, " personas es de $20,900")
  else:
    cost_hotel==13450
    print("El precio por noche del hotel para", pers, " personas es de $13,450")
  return cost_hotel
  
def taxi ():
  coti_taxi =int(input("¿Desea un taxi que lo lleve a su hotel? Si(1)"))
  if coti_taxi == 1:
    cost_taxi = 200
    print("El costo del taxi es: $ ",cost_taxi)
  else:
    cost_taxi = 0
    print("El costo del taxi es: $ ",cost_taxi)
  return cost_taxi
  
print("************************")
print("* BIENVENIDO A VIAJAJA *")
print("************************")
print("""¿Qué desea hacer?
0.Cotizar avión
1.Cotizar hotel
2.Cotización taxi
3.Hacer una cotización completa
4.Salir""")
opc=int(input())
while opc > 4:
  print("Escoja alguna de las 5 opciones ")
  opc=int(input())
if opc==0:
  pers = int(input("¿Para cuantas personas va ha ser la cotzación? (No se permite más de 10 personas)"))
  while pers > 10:
    print("No se permite más de 10 personas")
    pers = int(input("¿Para cuantas personas va ha ser la cotzación?" ))
  vuelo()
elif opc==1:
    pers = int(input("¿Para cuantas personas va ha ser la cotzación? (No se permite más de 10 personas)"))
    while pers > 10:
      print("No se permite más de 10 personas")
      pers = int(input("¿Para cuantas personas va ha ser la cotzación?" ))
    hotel()
elif opc==2:
    taxi()
elif opc==3:
    pers = int(input("¿Para cuantas personas va ha ser la cotzación? (No se permite más de 10 personas)"))
    while pers > 10:
      print("No se permite más de 10 personas")
      pers = int(input("¿Para cuantas personas va ha ser la cotzación?" ))
    costo_vuelo=vuelo()
    costo_hotel=hotel()
    costo_taxi=taxi()
    total=costo_vuelo+costo_hotel+costo_taxi
    print("El total de su cotización es $", total)
else:
  print("Tenga buen día")